{% if cookiecutter.include_docker_compose == "yes" %}
version: '3'

services:
  app:
    build: .
    ports:
      - "{{ cookiecutter.docker_expose_port }}:{{ cookiecutter.docker_expose_port }}"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
{% if cookiecutter.docker_compose_services == "postgres" or cookiecutter.docker_compose_services == "both" %}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB={{ cookiecutter.project_slug }}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
{% endif %}

{% if cookiecutter.docker_compose_services == "redis" or cookiecutter.docker_compose_services == "both" %}
    {% if cookiecutter.docker_compose_services != "both" %}
    depends_on:
      - redis
    {% endif %}

  redis:
    image: redis:6
    ports:
      - "6379:6379"
{% endif %}

{% if cookiecutter.docker_compose_services == "postgres" or cookiecutter.docker_compose_services == "both" %}
volumes:
  postgres_data:
{% endif %}
{% endif %}